name: music-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  # --- CUDA 12.1 CONFIGURATION ---
  - pytorch-cuda=12.1
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  # -------------------------------
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  # Removed specific libcu* libraries to allow CUDA 12 versions to install automatically
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0=openmpi
  - mpi4py=3.1.4
  - mpmath=1.2.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openmpi=4.0.4
  - openssl
  - pillow=9.4.0
  - pip=23.1.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - pytorch-mutex=1.0=cuda
  - readline=8.2
  - requests=2.31.0
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchtext=0.6.0
  - tqdm=4.65.0
  - typing_extensions=4.6.3
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - accelerate==0.21.0
    - anyio==4.0.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.1.0
    - awscli==1.29.84
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - bleach==6.1.0
    - blobfile==2.0.2
    - boltons==23.0.0
    - botocore==1.31.84
    - cachetools==5.3.1
    - chardet==5.1.0
    - clean-fid==0.1.35
    - click==8.1.3
    - clip-anytorch==2.5.2
    - colorama==0.4.4
    - comm==0.1.4
    - contextlib2==21.6.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - docutils==0.16
    - einops==0.6.1
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - fastjsonschema==2.18.1
    - fonttools==4.40.0
    - fqdn==1.5.1
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.21.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.56.0
    - huggingface-hub==0.15.1
    - imageio==2.31.1
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - ipykernel==6.26.0
    - ipython==8.17.2
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jmespath==1.0.1
    - joblib==1.3.1
    - json5==0.9.14
    - jsonmerge==1.9.2
    - jsonpickle==3.0.1
    - jsonpointer==2.4
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.5.0
    - jupyter-console==6.6.3
    - jupyter-core==5.5.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.9.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - k-diffusion==0.0.16
    - kiwisolver==1.4.4
    - kornia==0.7.0
    - lazy-loader==0.3
    - lmdb==1.4.1
    - lxml==4.9.2
    - markdown==3.4.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mido==1.2.10
    - mistune==3.0.2
    - ml-collections==0.1.1
    - more-itertools==10.0.0
    - music21==8.3.0
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - oauthlib==3.2.2
    - omegaconf==2.0.0
    - overrides==7.4.0
    - packaging==23.1
    - pandas==2.0.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - platformdirs==3.11.0
    - prometheus-client==0.18.0
    - prompt-toolkit==3.0.39
    - protobuf==4.23.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycryptodomex==3.18.0
    - pygments==2.16.1
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==1.0.8
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.1.1
    - qtconsole==5.4.4
    - qtpy==2.4.1
    - referencing==0.30.2
    - regex==2023.8.8
    - requests-oauthlib==1.3.1
    - resize-right==0.0.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rotary-embedding-torch==0.3.2
    - rpds-py==0.9.2
    - rsa==4.7.2
    - s3transfer==0.7.0
    - safetensors==0.3.1
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.11.2
    - seaborn==0.13.0
    - send2trash==1.8.2
    - sentry-sdk==1.25.1
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.3
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tifffile==2023.8.12
    - timm==0.9.2
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torchdata==0.6.1
    - torchdiffeq==0.2.3
    - torchsde==0.2.5
    - tornado==6.3.3
    - traitlets==5.13.0
    - trampoline==0.1.2
    - types-python-dateutil==2.8.19.14
    - tzdata==2023.3
    - uri-template==1.3.0
    - wandb==0.15.4
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - werkzeug==2.3.6
    - widgetsnbextension==4.0.9
    - zipp==3.15.0